# Generated by Django 3.2.8 on 2022-10-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.TextField()),
                ('industry_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.industry')),
                ('type_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.type')),
            ],
        ),
        migrations.CreateModel(
            name='Info_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.TextField(max_length=255)),
                ('meta_value', models.TextField(null=True)),
                ('info_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.information')),
            ],
        ),
    ]
