# Generated by Django 4.1.2 on 2022-11-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyh2', models.TextField()),
                ('valueh2', models.TextField(null=True)),
                ('key_h3', models.TextField()),
                ('key_h4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyh3', models.TextField(null=True)),
                ('valueh3', models.TimeField()),
                ('keyh4', models.TextField(null=True)),
                ('valueh4', models.TimeField()),
                ('Main_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.info_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.TextField()),
                ('industry_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.industry')),
                ('type_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.type')),
            ],
        ),
        migrations.AddField(
            model_name='info_meta',
            name='info_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='try_wiki_app.information'),
        ),
    ]
