# Generated by Django 3.2.8 on 2022-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try_wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
